### ISSUE TITLE
Issue at Step "6.3 Enable Approval Workflow"

### ISSUE THREAD

**Issue by hhbilgen** [SAP-samples/idm-business-extensions-service#1]
Hi,
on Page 69, guide mentions 
"You can also activate the workflow on repository level so that it is inherited to all privileges of
this repository. To do so please follow the steps:
..
Make sure that the tab Constants is enabled and maintain the following repository
constants based on your requirements:
o To find the correct process you can search for “approval”
o MX_VALIDATE_ADD_TASK
o MX_VALIDATE_DEL_TASK
o MX_VALIDATE_MOD_VALIDITY_TASK
"
But I cannot find those constants for any of the Repositories I've created.

Did I miss something?

Regards

**Comment by fastnodu** [comment]
Hi,

It seems that the constants are not configured correctly. You need to logon to Eclipse, navigate to your repository type and change the type of the constants from "Repository Type Constant" to "Repository Type Constant With Override". Then the constants are visible in the Admin UI. Alternatively, you can maintain the constants directly in Eclipse for the repository type. This is useful, for example, if you have five ABAP repositories that all use the same approval tasks. You can maintain the constants on the "General" tab of the repository type configuration or on tab "Event Process".

Hope this helps!

Kind regards,
Fabian

**Comment by hhbilgen** [comment]
Hi Fabian,

Thank you for prompt response. Constants are not visible/exits on Repository Type when I check in Eclipse. As you mentioned, I've tried to add (e.g. MX_VALIDATE_ADD_TASK) them on package com.sap.rds.idm.connector.abap > SAPC_ABAPSystem and got error "This is a reserved constant name. Enter another name for the constant"

**Comment by fastnodu** [comment]
Then you need to maintain the constants on tab "Event Process". I think the constants are then added.

![image](https://user-images.githubusercontent.com/46542985/149905138-559a0ee1-4a21-4e92-bf5e-1ae86738d8ce.png)

**Comment by hhbilgen** [comment]
Hi Fabian,
This way it works. But, for me, another missing part is to how to create the Processes like ValidateAdd/ValidateDelete/ValidateModValidity processes like you. Is there any guidance you can share with me?
Best Regards

**Comment by fastnodu** [comment]
Hi,

I think there are some approval (validation tasks) shipped with the approval package. Look at part 6.1  in the guide.
My processes are not default ones. I created these manually and put some logic into the processes (e.g. approval task, notifications, calculate approver and so on). The name follows an internal naming rule.

Kind regards,
Fabian

**Comment by NormanNuernberger** [comment]
Considering this a basis configuration question, not related to BE Service
