### ISSUE TITLE
Deploying BES-SP05

### ISSUE THREAD

**Issue by hhbilgen** [SAP-samples/idm-business-extensions-service#10]
Hi Team,

We've just deployed a fresh IDM 8.0 SP08 for a customer. I've to questions related to SP05:

1. On Page https://github.com/SAP-samples/idm-business-extensions-service **Requirements** says "**[SAP Identity Management](https://www.sap.com/products/identity-management.html) 8.0 SP08 (Schema Version 1814)**" is needed. Fresh system comes with Schema Version 1815. Is this a problem or we can go with installation?
2. In order to install SP08 on IDM 8.0 SP08, do we have to deploy SP04 first and then SP05?

Regards

**Comment by NormanNuernberger** [comment]
Hi Hüseyin,
1. This is not a problem 1814 is minimum requirement, everything higher is possible.
2. No you can go straight with SP05
Regards
 Norman

**Comment by NormanNuernberger** [comment]
replied
