### ISSUE TITLE
purpose for the SAPC_SHADOW_PERSON entry in the RDS project

### ISSUE THREAD

**Issue by jaoparaujo** [SAP-samples/idm-business-extensions-service#11]
Hey guys,

I would like to understand the purpose for the SAPC_SHADOW_PERSON entry in the RDS project.

Best regards, 

João Paulo.

**Comment by NormanNuernberger** [comment]
Hi João,
it is a vehicle to replicate concurrent employments from HCM into the HCM Staging Area of IdM, to enable that a real person will always be mapped to only one Person in IdM, even if he has multiple records inside HCM.
Regards
 Norman

**Comment by jaoparaujo** [comment]
Hi Norman, 

Thanks for the quick feedback.
I will see the best way to apply it to my project, I have a similar business requirement when hiring an intern or temporary employee.

Best regards,

João Paulo.
