### ISSUE TITLE
Release date for SP05

### ISSUE THREAD

**Issue by hhbilgen** [SAP-samples/idm-business-extensions-service#2]
Hi Team,
In our last INDUS Security SIG Meeting, you've mentioned that you'll release SP05 which is IDM 8.0 SP08 compatible version at the end of February. 
Can you please update us the release date of IDM-BE-SP05?
Regards

**Comment by NormanNuernberger** [comment]
Hi Huseyin,
sorry for late reply. SP05 has been released and uploaded.
Thanks 
 Norman
